<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\Component\Config\Definition\Configurator;

return static function (DefinitionConfigurator $configurator): void {
    $configurator->rootNode()
        ->children()
            ->scalarNode('app')->defaultValue('app')->end()
            ->scalarNode('version')->defaultValue('0.0.1')->end()
            ->scalarNode('description')->defaultNull()->end()
            ->arrayNode('icons')
                ->arrayPrototype()
                    ->children()
                        ->scalarNode('src')->isRequired()->end()
                        ->scalarNode('mime_type')->defaultNull()->end()
                        ->arrayNode('sizes')
                            ->scalarPrototype()->end()
                            ->defaultValue(['any'])
                        ->end()
                    ->end()
                ->end()
            ->end()
            ->scalarNode('website_url')->defaultNull()->end()
            ->integerNode('pagination_limit')->defaultValue(50)->end()
            ->scalarNode('instructions')->defaultNull()->end()
            ->arrayNode('client_transports')
                ->children()
                    ->booleanNode('stdio')->defaultFalse()->end()
                    ->booleanNode('http')->defaultFalse()->end()
                ->end()
            ->end()
            ->arrayNode('clients')
                ->info('MCP clients connecting outward to remote MCP servers.')
                ->useAttributeAsKey('name')
                ->arrayPrototype()
                    ->children()
                        ->enumNode('transport')
                            ->values(['stdio', 'http'])
                            ->isRequired()
                            ->info('Transport used to reach the server: a child process (stdio) or a remote HTTP endpoint.')
                        ->end()
                        ->arrayNode('command')
                            ->info('Command and arguments for stdio transport, e.g. ["npx", "-y", "@modelcontextprotocol/server-filesystem", "/tmp"].')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->scalarNode('cwd')->defaultNull()->info('Working directory for the stdio child process.')->end()
                        ->arrayNode('env')
                            ->info('Environment variables for the stdio child process.')
                            ->normalizeKeys(false)
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->scalarNode('url')->defaultNull()->info('Endpoint URL for HTTP transport.')->end()
                        ->arrayNode('headers')
                            ->info('Additional headers for HTTP transport (e.g. Authorization).')
                            ->normalizeKeys(false)
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->scalarNode('http_client')
                            ->info('Optional service id of a PSR-18 HTTP client to use instead of the auto-discovered one.')
                            ->defaultNull()
                        ->end()
                        ->arrayNode('client_info')
                            ->info('Identification advertised to the remote MCP server during the initialize handshake.')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('name')->defaultValue('symfony-mcp-bundle')->end()
                                ->scalarNode('version')->defaultValue('0.1')->end()
                                ->scalarNode('description')->defaultNull()->end()
                            ->end()
                        ->end()
                        ->integerNode('init_timeout')->min(1)->defaultValue(30)->end()
                        ->integerNode('request_timeout')->min(1)->defaultValue(120)->end()
                    ->end()
                    ->validate()
                        ->ifTrue(static fn (array $v): bool => 'stdio' === $v['transport'] && [] === $v['command'])
                        ->thenInvalid('A "command" must be configured for stdio transport.')
                    ->end()
                    ->validate()
                        ->ifTrue(static fn (array $v): bool => 'http' === $v['transport'] && null === $v['url'])
                        ->thenInvalid('A "url" must be configured for http transport.')
                    ->end()
                ->end()
                ->defaultValue([])
            ->end()
            ->arrayNode('discovery')
                ->addDefaultsIfNotSet()
                ->children()
                    ->arrayNode('scan_dirs')
                        ->scalarPrototype()->end()
                        ->defaultValue(['src'])
                    ->end()
                    ->arrayNode('exclude_dirs')
                        ->scalarPrototype()->end()
                        ->defaultValue([])
                    ->end()
                ->end()
            ->end()
            ->arrayNode('http')
                ->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('path')->defaultValue('/_mcp')->end()
                    ->arrayNode('session')
                        ->addDefaultsIfNotSet()
                        ->children()
                            ->enumNode('store')->values(['file', 'memory', 'cache', 'framework'])->defaultValue('file')->end()
                            ->scalarNode('directory')->defaultValue('%kernel.cache_dir%/mcp-sessions')->end()
                            ->scalarNode('cache_pool')->defaultValue('cache.mcp.sessions')->end()
                            ->scalarNode('prefix')->defaultValue('mcp-')->end()
                            ->integerNode('ttl')->min(1)->defaultValue(3600)->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
        ->end()
    ;
};
